# Generated by Django 6.0.3 on 2026-04-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100)),
                ('house_number', models.CharField(max_length=20)),
                ('flat_number', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('postal_code', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_date', models.DateTimeField(auto_now_add=True)),
                ('previous_status', models.CharField(max_length=50)),
                ('new_status', models.CharField(max_length=50)),
                ('note', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CANDIDATE', 'Candidate'), ('STUDENT', 'Student'), ('EXPELLED', 'Expelled')], default='DRAFT', max_length=50)),
                ('status_note', models.CharField(blank=True, max_length=200)),
                ('enrollment_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubmittedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('ACCEPTED', 'Accepted'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('SIGN & DELIVER', 'Delivery')], default='SUBMITTED', max_length=50)),
                ('submitted_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
