# Generated by Django 6.0.3 on 2026-03-28 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100)),
                ('house_number', models.CharField(max_length=20)),
                ('flat_number', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('postal_code', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('status_note', models.CharField(blank=True, max_length=200)),
                ('enrollment_date', models.DateTimeField()),
                ('studies_edition', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='studies.studiesedition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('second_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('family_name', models.CharField(blank=True, max_length=50)),
                ('academic_title', models.CharField(blank=True, max_length=50)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=50)),
                ('pesel', models.CharField(blank=True, max_length=11)),
                ('citizenship', models.CharField(blank=True, max_length=50)),
                ('education', models.CharField(blank=True, max_length=50)),
                ('education_country', models.CharField(blank=True, max_length=50)),
                ('emergency_contact', models.CharField(blank=True, max_length=100)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='enrollments.enrollment')),
                ('registered_address', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='registered_formdata', to='enrollments.address')),
                ('residential_address', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='residential_formdata', to='enrollments.address')),
            ],
        ),
        migrations.CreateModel(
            name='SubmittedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='submitted_documents/')),
                ('status', models.CharField(max_length=50)),
                ('submitted_date', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='enrollments.enrollment')),
                ('studies_document', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='studies.studiesdocument')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_date', models.DateTimeField(auto_now_add=True)),
                ('previous_status', models.CharField(max_length=50)),
                ('new_status', models.CharField(max_length=50)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='studies.studieseditionstaff')),
                ('submitted_document', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='enrollments.submitteddocument')),
            ],
        ),
    ]
