# Generated by Django 6.0.3 on 2026-04-01 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollments', '0001_initial'),
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenthistory',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='studies.studieseditionstaff'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='studies_edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='studies.studiesedition'),
        ),
    ]
