# Generated by Django 6.0.3 on 2026-04-27 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollments', '0001_initial'),
        ('files', '0001_initial'),
        ('studies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documenthistory',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='studies.studieseditionstaff'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='studies_edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='studies.studiesedition'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submitteddocument',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='enrollments.enrollment'),
        ),
        migrations.AddField(
            model_name='submitteddocument',
            name='file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='submitted_document', to='files.file'),
        ),
        migrations.AddField(
            model_name='submitteddocument',
            name='studies_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='submitted_documents', to='studies.studiesdocument'),
        ),
        migrations.AddField(
            model_name='documenthistory',
            name='submitted_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='enrollments.submitteddocument'),
        ),
        migrations.CreateModel(
            name='FormData',
            fields=[
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, related_name='form', serialize=False, to='enrollments.enrollment')),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('second_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('family_name', models.CharField(blank=True, max_length=50)),
                ('academic_title', models.CharField(blank=True, max_length=50)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=50)),
                ('pesel', models.CharField(blank=True, max_length=11)),
                ('citizenship', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('education_university', models.CharField(blank=True, max_length=50)),
                ('education_year', models.IntegerField(blank=True)),
                ('education_location', models.CharField(blank=True, max_length=50)),
                ('maturity_country', models.CharField(blank=True, max_length=50)),
                ('emergency_name', models.CharField(blank=True, max_length=50)),
                ('emergency_last_name', models.CharField(blank=True, max_length=50)),
                ('emergency_phone', models.CharField(blank=True, max_length=50)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('registered_address', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='registered_formdata', to='enrollments.address')),
                ('residential_address', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='residential_formdata', to='enrollments.address')),
            ],
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('user', 'studies_edition'), name='unique user enrollment per studies edition'),
        ),
    ]
