# Generated by Django 6.0.3 on 2026-04-01 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollments', '0002_initial'),
        ('studies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fees',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='fees', to='enrollments.enrollment'),
        ),
        migrations.AddField(
            model_name='formdata',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='enrollments.enrollment'),
        ),
        migrations.AddField(
            model_name='formdata',
            name='registered_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='registered_formdata', to='enrollments.address'),
        ),
        migrations.AddField(
            model_name='formdata',
            name='residential_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='residential_formdata', to='enrollments.address'),
        ),
        migrations.AddField(
            model_name='payments',
            name='fee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='payments', to='enrollments.fees'),
        ),
        migrations.AddField(
            model_name='paymentshistory',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='enrollments.payments'),
        ),
        migrations.AddField(
            model_name='submitteddocument',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='enrollments.enrollment'),
        ),
        migrations.AddField(
            model_name='submitteddocument',
            name='studies_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='studies.studiesdocument'),
        ),
        migrations.AddField(
            model_name='documenthistory',
            name='submitted_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='enrollments.submitteddocument'),
        ),
    ]
