# Generated by Django 6.0.3 on 2026-04-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='education_year',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
