# Generated by Django 6.0.3 on 2026-04-04 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_initial'),
        ('studies', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitteddocument',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('ACCEPTED', 'Accepted'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=50),
        ),
        migrations.AlterField(
            model_name='submitteddocument',
            name='studies_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='submitted_documents', to='studies.studiesdocument'),
        ),
    ]
