# Generated by Django 6.0.3 on 2026-05-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0003_alter_formdata_education_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('CANDIDATE', 'Candidate'), ('RESERVE', 'Reserve'), ('STUDENT', 'Student'), ('REJECTED', 'Rejected'), ('EXPELLED', 'Expelled')], default='DRAFT', max_length=50),
        ),
    ]
