# Generated by Django 6.0.4 on 2026-04-10 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0003_alter_submitteddocument_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='paymentshistory',
            name='payment',
        ),
        migrations.DeleteModel(
            name='Fees',
        ),
        migrations.DeleteModel(
            name='Payments',
        ),
        migrations.DeleteModel(
            name='PaymentsHistory',
        ),
    ]
