# Generated by Django 6.0.3 on 2026-04-02 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0003_initial'),
        ('studies', '0004_alter_studieseditionstaff_studies_edition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formdata',
            name='id',
        ),
        migrations.AddField(
            model_name='formdata',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='formdata',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('CANDIDATE', 'Candidate'), ('STUDENT', 'Student'), ('EXPELLED', 'Expelled')], default='DRAFT', max_length=50),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, serialize=False, to='enrollments.enrollment'),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='registered_address',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='residential_address',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('user', 'studies_edition'), name='unique user enrollment per studies edition'),
        ),
    ]
