# Generated by Django 6.0.3 on 2026-04-02 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0004_remove_formdata_id_formdata_email_formdata_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='enrollment_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
