# Generated by Django 6.0.3 on 2026-05-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0004_alter_enrollment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('CANDIDATE', 'Candidate'), ('RESERVE', 'Reserve'), ('STUDENT', 'Student'), ('REJECTED', 'Rejected'), ('EXPELLED', 'Expelled'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=50),
        ),
    ]
