# Generated by Django 6.0.3 on 2026-04-17 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0004_remove_payments_fee_remove_paymentshistory_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='enrollment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, related_name='form', serialize=False, to='enrollments.enrollment'),
        ),
        migrations.AlterField(
            model_name='submitteddocument',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('ACCEPTED', 'Accepted'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('SIGN & DELIVER', 'Delivery')], default='SUBMITTED', max_length=50),
        ),
    ]
