# Generated by Django 6.0.3 on 2026-04-02 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0005_alter_enrollment_enrollment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='enrollment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, serialize=False, to='enrollments.enrollment'),
        ),
    ]
