# Generated by Django 6.0.3 on 2026-04-20 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0005_alter_formdata_enrollment_and_more'),
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitteddocument',
            name='file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='submitted_document', to='files.file'),
        ),
    ]
