# Generated by Django 6.0.3 on 2026-04-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0006_alter_formdata_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='enrollment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
