# Generated by Django 6.0.3 on 2026-03-28 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Studies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('terms_count', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StudiesEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('max_participants', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('syllabus_url', models.URLField()),
                ('recruitment_start_date', models.DateTimeField()),
                ('recruitment_end_date', models.DateTimeField()),
                ('studies', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='studies.studies')),
            ],
        ),
        migrations.CreateModel(
            name='StudiesDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('required', models.BooleanField()),
                ('due_date', models.DateTimeField()),
                ('studies_edition', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='studies.studiesedition')),
            ],
        ),
        migrations.CreateModel(
            name='StudiesEditionStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('studies_edition', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='studies.studiesedition')),
            ],
        ),
    ]
