# Generated by Django 6.0.3 on 2026-04-01 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('terms_count', models.PositiveIntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StudiesEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('max_participants', models.IntegerField()),
                ('status', models.CharField(choices=[('HIDDEN', 'Hidden'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='HIDDEN', max_length=50)),
                ('syllabus_url', models.URLField()),
                ('recruitment_start_date', models.DateTimeField()),
                ('recruitment_end_date', models.DateTimeField()),
                ('studies', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='studies.studies')),
            ],
        ),
        migrations.CreateModel(
            name='StudiesDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('required', models.BooleanField()),
                ('due_date', models.DateTimeField()),
                ('studies_edition', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='studies.studiesedition')),
            ],
        ),
        migrations.CreateModel(
            name='StudiesEditionStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('STUDIES_DIRECTOR', 'Studies Director'), ('ADMINISTRATIVE_COORDINATOR', 'Administrative Coordinator'), ('FINANCE_COORDINATOR', 'Finance Coordinator')], max_length=50)),
                ('studies_edition', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='studies.studiesedition')),
            ],
        ),
    ]
