# Generated by Django 6.0.3 on 2026-03-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studies',
            name='terms_count',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='studiesedition',
            name='status',
            field=models.CharField(choices=[('HIDDEN', 'Hidden'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='HIDDEN', max_length=50),
        ),
    ]
