# Generated by Django 6.0.3 on 2026-04-27 16:16

import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studieseditionstaff',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='studies_edition_staff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='studiesedition',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='end_date_gt_start_date'),
        ),
        migrations.AddConstraint(
            model_name='studiesedition',
            constraint=models.CheckConstraint(condition=models.Q(('recruitment_end_date__gt', models.F('recruitment_start_date'))), name='recruitment_end_date_gt_recruitment_start_date'),
        ),
        migrations.AddConstraint(
            model_name='studiesedition',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__gte', models.F('recruitment_end_date'))), name='start_date_gte_recruitment_end_date'),
        ),
        migrations.AddConstraint(
            model_name='studiesedition',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='price_positive'),
        ),
        migrations.AddConstraint(
            model_name='studiesdocument',
            constraint=models.CheckConstraint(condition=models.Q(('due_date__gt', django.db.models.functions.datetime.Now())), name='due_date_in_future'),
        ),
        migrations.AddIndex(
            model_name='studieseditionstaff',
            index=models.Index(fields=['user', 'studies_edition'], name='studies_stu_user_id_a9aaca_idx'),
        ),
        migrations.AddIndex(
            model_name='studieseditionstaff',
            index=models.Index(fields=['studies_edition', 'role'], name='studies_stu_studies_1cc0e7_idx'),
        ),
        migrations.AddConstraint(
            model_name='studieseditionstaff',
            constraint=models.UniqueConstraint(fields=('studies_edition', 'user', 'role'), name='unique_studies_edition_staff_entry'),
        ),
    ]
