# Generated by Django 6.0.3 on 2026-05-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studiesedition',
            name='task_close_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studiesedition',
            name='task_open_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
