# Generated by Django 6.0.3 on 2026-04-06 10:56

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studiesedition',
            name='max_participants',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddConstraint(
            model_name='studiesdocument',
            constraint=models.CheckConstraint(condition=models.Q(('due_date__gt', django.db.models.functions.datetime.Now())), name='due_date_in_future'),
        ),
        migrations.AddConstraint(
            model_name='studiesedition',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='end_date_gt_start_date'),
        ),
        migrations.AddConstraint(
            model_name='studiesedition',
            constraint=models.CheckConstraint(condition=models.Q(('recruitment_end_date__gt', models.F('recruitment_start_date'))), name='recruitment_end_date_gt_recruitment_start_date'),
        ),
        migrations.AddConstraint(
            model_name='studiesedition',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__gte', models.F('recruitment_end_date'))), name='start_date_gte_recruitment_end_date'),
        ),
        migrations.AddConstraint(
            model_name='studiesedition',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='price_positive'),
        ),
    ]
