# Generated by Django 6.0.3 on 2026-04-01 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='studieseditionstaff',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='studies_edition_staff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='studieseditionstaff',
            index=models.Index(fields=['user', 'studies_edition'], name='studies_stu_user_id_a9aaca_idx'),
        ),
        migrations.AddIndex(
            model_name='studieseditionstaff',
            index=models.Index(fields=['studies_edition', 'role'], name='studies_stu_studies_1cc0e7_idx'),
        ),
    ]
