# Generated by Django 6.0.3 on 2026-04-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0003_alter_studiesedition_max_participants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studies',
            name='organizational_unit',
            field=models.CharField(default='unit', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studiesedition',
            name='academic_year',
            field=models.CharField(default='2025/2026', max_length=10),
            preserve_default=False,
        ),
    ]
