# Generated by Django 6.0.3 on 2026-05-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0003_studiesedition_task_close_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studiesedition',
            name='status',
            field=models.CharField(choices=[('HIDDEN', 'Hidden'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='HIDDEN', max_length=50),
        ),
    ]
