# Generated by Django 6.0.3 on 2026-04-02 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0003_alter_studieseditionstaff_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studieseditionstaff',
            name='studies_edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='studies_edition_staff', to='studies.studiesedition'),
        ),
    ]
