# Generated by Django 6.0.3 on 2026-04-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0004_studies_organizational_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studiesdocument',
            name='is_auto_generated',
            field=models.BooleanField(default=False),
        ),
    ]
