# Generated by Django 6.0.3 on 2026-04-17 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0005_studiesdocument_is_auto_generated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studiesdocument',
            old_name='is_auto_generated',
            new_name='is_read_only',
        ),
    ]
