# Generated by Django 6.0.4 on 2026-04-11 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_employee_user_is_employee_workphonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workphonenumber',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_phones', to='users.employee'),
        ),
    ]
