# Generated by Django 6.0.3 on 2026-04-20 19:47

import files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=files.models.file_upload_path)),
                ('source', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('PAYMENT', 'Payment')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
